config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'dashboard#show'

  get '/signin', to: 'session#signin'
  get '/signout', to: 'session#signout'
  get '/signup', to: 'session#signup'

  get 'auth/signin'
  get 'auth/signout'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :books, only: %i[index show] do
    resources :bookcases, only: [] do
      resource :book_in_bookcase, controller: 'books/bookcases/book_in_bookcase', only: %i[create destroy]
    end
  end

  resources :users, param: :name, only: [:show], path: '/' do
    resources :bookcases, controller: 'users/bookcases' do
      member do
        get 'bookcase'
      end

      resources :book_in_bookcases, controller: 'users/bookcases/book_in_bookcases', only: %i[show destroy]
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :bookcase, dependent: :destroy
  has_many :cognito_sessions, dependent: :destroy

  validates :name, :subscriber, uniqueness: true
end

app/controllers/books/bookcases/book_in_bookcase_controller.rb
# frozen_string_literal: true

module Books
  module Bookcases
    class BookInBookcaseController < ApplicationController
      before_action :set_book_in_bookcase, only: %(destroy)

      def create
        @book_in_bookcase = BookInBookcase.new(book_in_bookcase_params)
        authorize @book_in_bookcase

        respond_to do |format|
          if @book_in_bookcase.save
            format.html do
              redirect_to book_url(@book_in_bookcase.book),
                          notice: I18n.t('books.bookcases.book_in_bookcases.added_book_to_the_bookcase',
                                         bookcase_name: @book_in_bookcase.bookcase.name)
            end
          end
        end
      end

      def destroy
        authorize @book_in_bookcase

        respond_to do |format|
          if @book_in_bookcase.destroy
            format.html do
              redirect_to book_url(@book_in_bookcase.book),
                          notice: I18n.t('books.bookcases.book_in_bookcases.take_out_a_book_from_the_bookcase',
                                         bookcase_name: @book_in_bookcase.bookcase.name)
            end
            format.json { head :no_content }
          end
        end
      end

      private

      def set_book_in_bookcase
        @book_in_bookcase = BookInBookcase.find_by!(bookcase_id: params[:bookcase_id], book_id: params[:book_id])
      end

      def book_in_bookcase_params
        params.permit(:bookcase_id, :book_id)
      end
    end
  end
end

app/controllers/users/bookcases/book_in_bookcases_controller.rb
# frozen_string_literal: true

module Users
  module Bookcases
    class BookInBookcasesController < ApplicationController
      before_action :set_user, only: %i[show destroy]
      before_action :set_bookcase, only: %i[show destroy]
      before_action :set_book_in_bookcase, only: %i[show destroy]

      def show
        authorize @book_in_bookcase
      end

      def destroy
        authorize @book_in_bookcase
        @book_in_bookcase.destroy

        respond_to do |format|
          format.html do
            redirect_to user_bookcase_url(@user.name, @bookcase),
                        notice: I18n.t('users.bookcases.book_in_bookcases.off_the_bookcase',
                                       title: @book_in_bookcase.book.title)
          end
          format.json { head :no_content }
        end
      end

      private

      def set_user
        @user = User.find_by!(name: params[:user_name])
      end

      def set_bookcase
        @bookcase = Bookcase.owned_by(@user).find(params[:bookcase_id])
      end

      def set_book_in_bookcase
        @book_in_bookcase = BookInBookcase.find_by!(id: params[:id], bookcase: @bookcase)
      end
    end
  end
end

app/controllers/users/bookcases_controller.rb
# frozen_string_literal: true

module Users
  class BookcasesController < ApplicationController
    before_action :set_user
    before_action :set_bookcase, only: %i[edit update destroy bookcase]

    def index
      @bookcases = Bookcase.owned_by(@user)
      @new_bookcase = Bookcase.new(user: @user)
      authorize Bookcase
    end

    def show
      @bookcase = Bookcase.owned_by(@user).eager_load(book_in_bookcase: { book: :authors }).find(params[:id])

      authorize @bookcase
    end

    def new
      @bookcase = Bookcase.new(user: @user)
      authorize @bookcase
    end

    def edit
      authorize @bookcase
    end

    def create
      @bookcase = Bookcase.new(bookcase_params)
      authorize @bookcase

      return if @bookcase.save

      render :new, status: :unprocessable_entity
    end

    def update
      authorize @bookcase
      respond_to do |format|
        if @bookcase.update(bookcase_params)
          format.turbo_stream
          format.json { render :show, status: :ok, location: @bookcase }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @bookcase.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      authorize @bookcase
      @bookcase.destroy

      respond_to do |format|
        format.html { redirect_to user_bookcases_url, notice: I18n.t('users.bookcases.destroyed_success') }
        format.json { head :no_content }
      end
    end

    def bookcase
      @bookcase = Bookcase.owned_by(@user).find(params[:id])
    end

    private

    def set_user
      @user = User.find_by!(name: params[:user_name])
    end

    def set_bookcase
      @bookcase = Bookcase.owned_by(@user).find(params[:id])
    end

    def bookcase_params
      params.require(:bookcase).permit(:name, :user_id)
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show]

  def show; end

  def set_user
    @user = User.find_by!(name: params[:name])
  end
end

app/views/users/bookcases/_form.html.slim
ruby:
  if action_name == 'new'
    url = user_bookcases_path
    title = t('users.bookcases.new.title')
  else
    url = user_bookcase_path(@bookcase.user.name, @bookcase)
    title = t('users.bookcases.edit.title')
  end

= turbo_frame_tag bookcase do
  = form_with(model: @bookcase, url:, data: { action: 'turbo:submit-end->modal#close' }) do |form|
    .bg-white.px-4.pb-4.pt-5.sm:p-6.sm:pb-4
      .sm:flex.sm:items-start
        .mt-3.text-center.sm:mt-0.sm:text-left.w-full
          h3#modal-title.text-base.font-semibold.leading-6.text-gray-900
            = title
          .mt-2
            .col-span-full
              = form.label :name,
                class: ['block text-sm font-medium leading-6 text-gray-900',
                  (bookcase.errors[:name].empty? ? '' : ' text-red-500')]
              .mt-2
                = form.text_field :name,
                  class: ['block w-full rounded-md py-1.5 text-gray-900 shadow-sm sm:text-sm sm:leading-6',
                    'border-0 ring-1 ring-inset ring-gray-300',
                    'focus:ring-2 focus:ring-inset focus:ring-indigo-600',
                    (bookcase.errors[:name].empty? ? '' : ' ring-red-500')]
              p.text-sm.leading-6.text-red-500 = bookcase.errors.full_messages_for(:name).join(' ')

    .bg-gray-50.px-4.py-3.sm:flex.sm:flex-row-reverse.sm:px-6
      = form.hidden_field :user_id, value: @bookcase.user.id
      = form.submit class: 'inline-flex w-full justify-center rounded-md bg-green-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-green-700 sm:ml-3 sm:w-auto'
      button.mt-3.inline-flex.w-full.justify-center.rounded-md.bg-white.px-3.py-2.text-sm.font-semibold.text-gray-900.shadow-sm.ring-1.ring-inset.ring-gray-300.hover:bg-gray-50.sm:mt-0.sm:w-auto[type="button" data-action="click->modal#cancel"]
        = t('users.bookcases.cancel')

app/views/users/bookcases/bookcase.html.slim
= turbo_frame_tag :bookcase
  = @bookcase.name

app/views/users/bookcases/edit.html.slim
= render 'modal' do
  = render 'form', bookcase: @bookcase

app/views/users/bookcases/index.html.slim
- provide(:title, t('Bookcases'))

= content_for(:action_buttons) do
  - if policy(@new_bookcase).new?
    = link_to t('.new_bookcase'), new_user_bookcase_path,
        class: 'bg-green-600 hover:bg-green-700 text-white rounded-md p-3 mx-1 px-4',
        data: { turbo_frame: 'modal' }

ul#bookcases.grid.grid-cols-1.gap-6.sm:grid-cols-2.lg:grid-cols-3
  - @bookcases.each do |bookcase|
    li.col-span-1.divide-y.divide-gray-200.rounded-lg.bg-white.shadow[id="#{dom_id bookcase}"]
      = link_to user_bookcase_path(bookcase.user.name, bookcase) do
        .flex.w-full.items-center.justify-between.space-x-6.p-6
          h3.text-sm.font-medium.text-gray-900
            = bookcase.name
          p.mt-1.text-sm.text-glay-500
            = t('.book_count', count: bookcase.books.count)

app/views/users/bookcases/new.html.slim
= render 'modal' do
  = render 'form', bookcase: @bookcase

app/views/users/bookcases/show.html.slim
- provide(:title, t('Bookcases'))

.rounded-lg.bg-white.shadow
  .px-4.py-5.sm:p-6
    = link_to t('.back_to_bookcases'), user_bookcases_path(@bookcase.user.name), class: 'text-blue-600'

    h2.text-lg.font-semibold.leading-10.text-gray-900
      = turbo_frame_tag :bookcase, src: bookcase_user_bookcase_path(@bookcase.user.name, @bookcase)

    .mt-6.flex.items-center.justify-end.gap-x-4
      - if policy(@bookcase).edit?
        = link_to t('.edit_this_bookcase'),
            edit_user_bookcase_path(@bookcase.user.name, @bookcase),
            class: 'bg-green-600 hover:bg-green-700 text-white rounded-md p-2 mx-1 px-4',
            data: { turbo_frame: 'modal' }

      - if policy(@bookcase).destroy?
        = button_to t('.destroy_this_bookcase'),
            user_bookcase_path(@bookcase.user.name, @bookcase),
            method: :delete, data: { turbo_confirm: t('.are_you_sure_you_want_to_destroy_this_bookcase') },
            class: 'bg-red-600 hover:bg-red-700 text-white rounded-md p-2 mx-1 px-4'

    .mt-2
      ul#books.grid.grid-cols-1.gap-6.sm:grid-cols-2.lg:grid-cols-3
        - @bookcase.book_in_bookcase.each do |book_in_bookcase|
          = link_to user_bookcase_book_in_bookcase_path(@bookcase.user.name, @bookcase, book_in_bookcase)
            = render 'books/books_panel_item', book: book_in_bookcase.book

app/views/users/bookcases/update.turbo_stream.html.slim
= turbo_stream.replace @bookcase
  = render 'bookcase'