config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'dashboard#show'

  get '/signin', to: 'session#signin'
  get '/signout', to: 'session#signout'
  get '/signup', to: 'session#signup'

  get 'auth/signin'
  get 'auth/signout'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :books, only: %i[index show] do
    resources :bookcases, only: [] do
      resource :book_in_bookcase, controller: 'books/bookcases/book_in_bookcase', only: %i[create destroy]
    end
  end

  resources :users, param: :name, only: [:show], path: '/' do
    resources :bookcases, controller: 'users/bookcases' do
      member do
        get 'bookcase'
      end

      resources :book_in_bookcases, controller: 'users/bookcases/book_in_bookcases', only: %i[show destroy]
    end
  end
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  has_many :book_authors, dependent: :destroy
  has_many :authors, through: :book_authors

  validates :title, :description, :page, :image_url, presence: true
  validate :required_either_isbn_or_asin

  private

  def required_either_isbn_or_asin
    return if isbn.present? ^ asin.present?

    errors.add(:base, I18n.t('.book.required_either_isbn_or_asin'))
  end
end

app/controllers/books/bookcases/book_in_bookcase_controller.rb
# frozen_string_literal: true

module Books
  module Bookcases
    class BookInBookcaseController < ApplicationController
      before_action :set_book_in_bookcase, only: %(destroy)

      def create
        @book_in_bookcase = BookInBookcase.new(book_in_bookcase_params)
        authorize @book_in_bookcase

        respond_to do |format|
          if @book_in_bookcase.save
            format.html do
              redirect_to book_url(@book_in_bookcase.book),
                          notice: I18n.t('books.bookcases.book_in_bookcases.added_book_to_the_bookcase',
                                         bookcase_name: @book_in_bookcase.bookcase.name)
            end
          end
        end
      end

      def destroy
        authorize @book_in_bookcase

        respond_to do |format|
          if @book_in_bookcase.destroy
            format.html do
              redirect_to book_url(@book_in_bookcase.book),
                          notice: I18n.t('books.bookcases.book_in_bookcases.take_out_a_book_from_the_bookcase',
                                         bookcase_name: @book_in_bookcase.bookcase.name)
            end
            format.json { head :no_content }
          end
        end
      end

      private

      def set_book_in_bookcase
        @book_in_bookcase = BookInBookcase.find_by!(bookcase_id: params[:bookcase_id], book_id: params[:book_id])
      end

      def book_in_bookcase_params
        params.permit(:bookcase_id, :book_id)
      end
    end
  end
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  before_action :set_book, only: %i[show]

  def index
    @books = Book.eager_load(:authors)
    authorize Book
  end

  def show
    @bookcases = Bookcase.owned_by(current_user)
    authorize @book
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end
end

app/views/books/_book.html.slim
h2.text-lg.font-semibold.leading-10.text-gray-900
  = book.title

.grid
  = image_tag(book.image_url, class: 'place-self-center w-60')

.space-y-12
  .border-b.border-gray-900/10.pb-2
    dl.divide-y.divide-gray-100[id="#{dom_id book}"]
      .px-4.py-6.sm:grid.sm:grid-cols-3.sm:gap-4.sm:px-0
        dt.text-sm.font-medium.leading-6.text-gray-900
          = Book.human_attribute_name(:authors)
        dd.mt-1.text-sm.leading-6.text-gray-700.sm:col-span-2.sm:mt-0
          = book.authors.map(&:name).join(', ')

      .px-4.py-6.sm:grid.sm:grid-cols-3.sm:gap-4.sm:px-0
        dt.text-sm.font-medium.leading-6.text-gray-900
          = Book.human_attribute_name(:description)
        dd.mt-1.text-sm.leading-6.text-gray-700.sm:col-span-2.sm:mt-0
          = book.description

      .px-4.py-6.sm:grid.sm:grid-cols-3.sm:gap-4.sm:px-0
        dt.text-sm.font-medium.leading-6.text-gray-900
          = Book.human_attribute_name(:page)
        dd.mt-1.text-sm.leading-6.text-gray-700.sm:col-span-2.sm:mt-0
          = book.page

      - if book.isbn
        .px-4.py-6.sm:grid.sm:grid-cols-3.sm:gap-4.sm:px-0
          dt.text-sm.font-medium.leading-6.text-gray-900
            = Book.human_attribute_name(:isbn)
          dd.mt-1.text-sm.leading-6.text-gray-700.sm:col-span-2.sm:mt-0
            = book.isbn

      - if book.asin
        .px-4.py-6.sm:grid.sm:grid-cols-3.sm:gap-4.sm:px-0
          dt.text-sm.font-medium.leading-6.text-gray-900
            = Book.human_attribute_name(:asin)
          dd.mt-1.text-sm.leading-6.text-gray-700.sm:col-span-2.sm:mt-0
            = book.asin

app/views/books/_books_panel_item.html.slim
.flex.w-full.items-center.justify-between.space-x-6.p-6
  .flex-1.truncate
    .grid
      = image_tag(book.image_url, class: 'place-self-center w-48')

    .flex.items-center.space-x-3
      h2.text-lg.font-medium.text-gray-900
        = book.title

    p.mt-1.truncate.text-sm.text-gray-500
      = book.authors.map(&:name).join(' ')

app/views/books/index.html.slim
- provide(:title, 'Books')

ul#books.grid.grid-cols-1.gap-6.sm:grid-cols-2.lg:grid-cols-3
  - @books.each do |book|
    li.col-span-1.divide-y.divide-gray-200.rounded-lg.bg-white.shadow[id="#{dom_id book}"]
      = link_to book_path(book)
        = render 'books_panel_item', book:

app/views/books/show.html.slim
- provide(:title, 'Books')

.rounded-lg.bg-white.shadow
  .px-4.py-5.sm:p-6
    = link_to t('.back_to_books'), books_path, class: 'text-blue-600'

    == render @book

    ul
      - @bookcases.each do |bookcase|
        li
          - if bookcase.already_inside?(@book)
            = link_to book_bookcase_book_in_bookcase_path(@book, bookcase), data: { 'turbo-method': :delete }, class: 'text-red-600'
              = t('.remove_from_bookcase', bookcase_name: bookcase.name)
          - else
            = link_to book_bookcase_book_in_bookcase_path(@book, bookcase), data: { 'turbo-method': :post }, class: 'text-green-600'
              = t('.add_to_bookcase', bookcase_name: bookcase.name)