config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'dashboard#show'

  get '/signin', to: 'session#signin'
  get '/signout', to: 'session#signout'
  get '/signup', to: 'session#signup'

  get 'auth/signin'
  get 'auth/signout'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :books, only: %i[index show] do
    resources :bookcases, only: [] do
      resource :book_in_bookcase, controller: 'books/bookcases/book_in_bookcase', only: %i[create destroy]
    end
  end

  resources :users, param: :name, only: [:show], path: '/' do
    resources :bookcases, controller: 'users/bookcases' do
      member do
        get 'bookcase'
      end

      resources :book_in_bookcases, controller: 'users/bookcases/book_in_bookcases', only: %i[show destroy]
    end
  end
end

app/views/layouts/_dropdown_menu.html.slim
.absolute.right-0.z-10.mt-2.w-48.origin-top-right.rounded-md.bg-white.py-1.shadow-lg.ring-1.ring-black.ring-opacity-5.focus:outline-none.hidden[
  data-dropdown-menu-target="menu"
  data-transition-enter="transition ease-out duration-100"
  data-transition-enter-start="transform opacity-0 scale-95"
  data-transition-enter-end="transform opacity-100 scale-100"
  data-transition-leave="transition ease-in duration-75"
  data-transition-leave-start="transform opacity-100 scale-100"
  data-transition-leave-end="transform opacity-0 scale-95"
  tabindex="-1"
]
  a#user-menu-item-0.block.px-4.py-2.text-sm.text-gray-700[href="#" tabindex="-1"]
    | Your Profile
  a#user-menu-item-1.block.px-4.py-2.text-sm.text-gray-700[href="#" tabindex="-1"]
    | Settings
  a#user-menu-item-2.block.px-4.py-2.text-sm.text-gray-700[href=signout_path tabindex="-1"]
    | Sign out

app/views/layouts/_mobile_menu.html.slim
#mobile-menu.md:hidden.hidden[
  data-mobile-menu-target="mobileMenu"
]
  .space-y-1.px-2.pb-3.pt-2.sm:px-3
    = link_to t('dashboard.show.title'), root_path, class: mobile_menu_item_class(t('dashboard.show.title'), yield(:title))
    - if @is_signed_in
      = link_to Bookcase.model_name.human(count: 2), user_bookcases_path(@current_user.name), class: mobile_menu_item_class(Bookcase.model_name.human(count: 2), yield(:title))
    = link_to Book.model_name.human(count: 2), books_path, class: mobile_menu_item_class(Book.model_name.human(count: 2), yield(:title))

  .border-t.border-gray-700.pb-3.pt-4
    .flex.items-center.px-5
      - if @is_signed_in
        .flex-shrink-0
          img.h-10.w-10.rounded-full[src=@current_user.avatar_url alt=@current_user.name]
        .ml-3
          .text-base.font-medium.leading-none.text-white
            = @current_user.name
          .text-sm.font-medium.leading-none.text-gray-400
            = @current_user.email
        button.ml-auto.flex-shrink-0.rounded-full.bg-gray-800.p-1.text-gray-400.hover:text-white.focus:outline-none.focus:ring-2.focus:ring-white.focus:ring-offset-2.focus:ring-offset-gray-800[type="button"]
          span.sr-only
            | View notifications
          svg.h-6.w-6[fill="none" viewbox="0 0 24 24" stroke-width="1.5" stroke="currentColor"]
            path[stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0"]

    - if @is_signed_in
      .mt-3.space-y-1.px-2
        a.block.rounded-md.px-3.py-2.text-base.font-medium.text-gray-400.hover:bg-gray-700.hover:text-white[href="#"]
          | Your Profile
        a.block.rounded-md.px-3.py-2.text-base.font-medium.text-gray-400.hover:bg-gray-700.hover:text-white[href="#"]
          | Settings
        a.block.rounded-md.px-3.py-2.text-base.font-medium.text-gray-400.hover:bg-gray-700.hover:text-white
          | Sign out
    - else
      .px-2
        a.block.rounded-md.px-3.py-2.text-base.font-medium.text-gray-400.hover:bg-gray-700.hover:text-white
          | Sign in
        a.block.rounded-md.border.border-gray-200.px-3.py-2.text-base.font-medium.text-gray-400.hover:bg-gray-700.hover:text-white
          | Sign up

app/views/layouts/_toast.html.slim
- if notice
  #toast-success.flex.items-center.w-full.max-w-sm.p-4.mb-4.text-gray-500.bg-white.rounded-lg.shadow.dark:text-gray-400.dark:bg-gray-800.md:max-w-xs[
    data-controller="toast"
    data-toast-target="notice"
    data-transition-enter="transition ease-out duration-100"
    data-transition-enter-start="translate-y-4 opacity-0 sm:translate-y-0 sm:translate-x-4"
    data-transition-enter-end="translate-y-0 opacity-100 sm:translate-x-0"
    data-transition-leave="translate-y-0 opacity-100 sm:translate-y-0"
    data-transition-leave-start="opacity-100"
    data-transition-leave-end="opacity-0"
    role="alert"
  ]
    .inline-flex.items-center.justify-center.flex-shrink-0.w-8.h-8.text-green-500.bg-green-100.rounded-lg.dark:bg-green-800.dark:text-green-200
      svg.w-5.h-5[aria-hidden="true" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"]
        path[fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"]
      span.sr-only
        | Check icon
    .ml-3.text-sm.font-normal
      = notice
    button.ml-auto.-mx-1.5.-my-1.5.bg-white.text-gray-400.hover:text-gray-900.rounded-lg.focus:ring-2.focus:ring-gray-300.p-1.5.hover:bg-gray-100.inline-flex.h-8.w-8.dark:text-gray-500.dark:hover:text-white.dark:bg-gray-800.dark:hover:bg-gray-700[type="button" aria-label="Close" data-action="toast#close"]
      span.sr-only
        | Close
      svg.w-5.h-5[aria-hidden="true" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"]
        path[fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"]

- elsif alert
  #toast-danger.flex.items-center.w-full.max-w-sm.p-4.mb-4.text-gray-500.bg-white.rounded-lg.shadow.dark:text-gray-400.dark:bg-gray-800.md:max-w-xs[
    data-controller="toast"
    data-toast-target="notice"
    data-transition-enter="transition ease-out duration-100"
    data-transition-enter-start="translate-y-4 opacity-0 sm:translate-y-0 sm:translate-x-4"
    data-transition-enter-end="translate-y-0 opacity-100 sm:translate-x-0"
    data-transition-leave="translate-y-0 opacity-100 sm:translate-y-0"
    data-transition-leave-start="opacity-100"
    data-transition-leave-end="opacity-0"
    role="alert"
  ]
    .inline-flex.items-center.justify-center.flex-shrink-0.w-8.h-8.text-red-500.bg-red-100.rounded-lg.dark:bg-red-800.dark:text-red-200
      svg.w-5.h-5[aria-hidden="true" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"]
        path[fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"]
      span.sr-only
        | Error icon
    .ml-3.text-sm.font-normal
      = alert
    button.ml-auto.-mx-1.5.-my-1.5.bg-white.text-gray-400.hover:text-gray-900.rounded-lg.focus:ring-2.focus:ring-gray-300.p-1.5.hover:bg-gray-100.inline-flex.h-8.w-8.dark:text-gray-500.dark:hover:text-white.dark:bg-gray-800.dark:hover:bg-gray-700[type="button" data-dismiss-target="#toast-danger" aria-label="Close"]
      span.sr-only
        | Close
      svg.w-5.h-5[aria-hidden="true" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"]
        path[fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"]

app/views/layouts/application.html.slim
doctype html
html.h-full.bg-gray-100
  head
    title
      | Bookshelf
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'tailwind', 'inter-font', 'data-turbo-track': 'reload'
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_importmap_tags

body.h-full
  .min-h-full
    nav.bg-gray-800
      .mx-auto.max-w-7xl.px-4.sm:px-6.lg:px-8[
          data-controller="mobile-menu"
        ]
        .flex.h-16.items-center.justify-between
          .flex.items-center
            .flex-shrink-0
              img.h-8.w-8[src="/site-image.png" alt="Your Company"]

            .hidden.md:block
              .ml-10.flex.items-baseline.space-x-4
                = link_to t('dashboard.show.title'), root_path, class: menu_item_class(t('dashboard.show.title'), yield(:title))
                - if @is_signed_in
                  = link_to Bookcase.model_name.human(count: 2), user_bookcases_path(@current_user.name), class: menu_item_class(Bookcase.model_name.human(count: 2), yield(:title))
                = link_to Book.model_name.human(count: 2), books_path, class: menu_item_class(Book.model_name.human(count: 2), yield(:title))

          .hidden.md:block
            .ml-4.flex.items-center.md:ml-6.space-x-2[
              data-controller="dropdown-menu"
            ]
              - if @is_signed_in
                button.rounded-full.bg-gray-800.p-1.text-gray-400.hover:text-white.focus:outline-none.focus:ring-2.focus:ring-white.focus:ring-offset-2.focus:ring-offset-gray-800[type="button"]
                  span.sr-only
                    | View notifications
                  svg.h-6.w-6[fill="none" viewbox="0 0 24 24" stroke-width="1.5" stroke="currentColor"]
                    path[stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0"]

                .relative.ml-3
                  div
                    button#user-menu-button.flex.max-w-xs.items-center.rounded-full.bg-gray-800.text-sm.focus:outline-none.focus:ring-2.focus:ring-white.focus:ring-offset-2.focus:ring-offset-gray-800[
                        data-action="dropdown-menu#toggleMenu"
                        type="button"
                      ]
                      span.sr-only
                        | Open user menu
                      img.h-8.w-8.rounded-full[src=@current_user.avatar_url alt=@current_user.name]

                  = render partial: 'layouts/dropdown_menu'

              - else
                = button_to 'Sign in', 'auth/cognito-idp', method: :post

          .-mr-2.flex.md:hidden
            / Mobile menu button
            button.inline-flex.items-center.justify-center.rounded-md.bg-gray-800.p-2.text-gray-400.hover:bg-gray-700.hover:text-white.focus:outline-none.focus:ring-2.focus:ring-white.focus:ring-offset-2.focus:ring-offset-gray-800[
                data-action="mobile-menu#toggleMenu"
                type="button"
              ]
              span.sr-only
                | Open main menu
              svg.block.h-6.w-6[fill="none" viewbox="0 0 24 24" stroke-width="1.5" stroke="currentColor"]
                path[stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5"]
              svg.hidden.h-6.w-6[fill="none" viewbox="0 0 24 24" stroke-width="1.5" stroke="currentColor"]
                path[stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"]

        = render partial: 'layouts/mobile_menu'

    header.grid.grid-flow-col.justify-between.bg-white.shadow
      .px-4.py-6.sm:px-6.lg:px-8
        h1.text-3xl.font-bold.tracking-tight.text-gray-900
          = yield(:title)

      .px-4.py-6.sm:px-6.lg:px-8
        = yield(:action_buttons)

    main
      .mx-auto.max-w-7xl.py-6.sm:px-6.lg:px-8
        = yield

  #flashes.fixed.top-0.end-0.m-3
    = render partial: 'layouts/toast'

app/views/layouts/maintenance.html.slim
doctype html
html.h-full.bg-gray-100
  head
    title
      | Bookshelf
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'tailwind', 'inter-font', 'data-turbo-track': 'reload'
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_importmap_tags

body.h-full
  .min-h-full
    nav.bg-gray-800
      .mx-auto.max-w-7xl.px-4.sm:px-6.lg:px-8[
          data-controller="mobile-menu"
        ]
        .flex.h-16.items-center.justify-between
          .flex.items-center
            .flex-shrink-0
              img.h-8.w-8[src="/site-image.png" alt="Your Company"]

          .hidden.md:block
            .ml-4.flex.items-center.md:ml-6.space-x-2[
              data-controller="dropdown-menu"
            ]
              - if @is_signed_in
                button.rounded-full.bg-gray-800.p-1.text-gray-400.hover:text-white.focus:outline-none.focus:ring-2.focus:ring-white.focus:ring-offset-2.focus:ring-offset-gray-800[type="button"]
                  span.sr-only
                    | View notifications
                  svg.h-6.w-6[fill="none" viewbox="0 0 24 24" stroke-width="1.5" stroke="currentColor"]
                    path[stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0"]

                .relative.ml-3
                  div
                    button#user-menu-button.flex.max-w-xs.items-center.rounded-full.bg-gray-800.text-sm.focus:outline-none.focus:ring-2.focus:ring-white.focus:ring-offset-2.focus:ring-offset-gray-800[
                        data-action="dropdown-menu#toggleMenu"
                        type="button"
                      ]
                      span.sr-only
                        | Open user menu
                      img.h-8.w-8.rounded-full[src=@current_user.avatar_url alt=@current_user.name]

                  = render partial: 'layouts/dropdown_menu'

              - else
                a.text-gray-300.hover:bg-gray-700.hover:text-white.rounded-md.px-3.py-2.text-sm.font-medium[href=signin_path]
                  | Sign in
                a.text-gray-300.hover:bg-gray-700.hover:text-white.rounded-md.border.border-gray-200.px-3.py-2.text-sm.font-medium[href=signup_path]
                  | Sign up

          .-mr-2.flex.md:hidden
            / Mobile menu button
            button.inline-flex.items-center.justify-center.rounded-md.bg-gray-800.p-2.text-gray-400.hover:bg-gray-700.hover:text-white.focus:outline-none.focus:ring-2.focus:ring-white.focus:ring-offset-2.focus:ring-offset-gray-800[
                data-action="mobile-menu#toggleMenu"
                type="button"
              ]
              span.sr-only
                | Open main menu
              svg.block.h-6.w-6[fill="none" viewbox="0 0 24 24" stroke-width="1.5" stroke="currentColor"]
                path[stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5"]
              svg.hidden.h-6.w-6[fill="none" viewbox="0 0 24 24" stroke-width="1.5" stroke="currentColor"]
                path[stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"]

        = render partial: 'layouts/mobile_menu'

    header.grid.grid-flow-col.justify-between.bg-white.shadow
      .px-4.py-6.sm:px-6.lg:px-8
        h1.text-3xl.font-bold.tracking-tight.text-gray-900
          = yield(:title)

      .px-4.py-6.sm:px-6.lg:px-8
        = yield(:action_buttons)

    main
      .mx-auto.max-w-7xl.py-6.sm:px-6.lg:px-8
        = yield

  #flashes.fixed.top-0.end-0.m-3
    = render partial: 'layouts/toast'